import profile1 from "../../assets/icons/pendingPayments/profile1.jpg"
import profile2 from "../../assets/icons/pendingPayments/profile2.jpg"
import profile3 from "../../assets/icons/pendingPayments/profile3.jpg"
import profile4 from "../../assets/icons/pendingPayments/profile4.jpg"
import profile5 from "../../assets/icons/pendingPayments/profile5.jpg"
import profile6 from "../../assets/icons/pendingPayments/profile6.jpg"

export const pendingPaymentRequests2 = [
  {
    id: 1,
    doctorName: "Isabel Wiza",
    email: "alinamath@gmail.com",
    mobile: "+91 8805322849",
    amountWithdrawal: "4,290",
    requestedDate: "1 Feb 2024",
    walletAmount: "30,000",
    status: "Paid",
    approvalDate: "1 October, 2023",
    icon: profile1,
  },
  {
    id: 2,
    doctorName: "Soumya Maheswari",
    email: "alinamath@gmail.com",
    mobile: "+91 8805322849",
    amountWithdrawal: "5,290",
    requestedDate: "1 Feb 2024",
    walletAmount: "30,000",
    status: "Decline",
    approvalDate: "2 July, 2023",
    icon: profile2,
  },
  {
    id: 3,
    doctorName: "Margie O’Reilley",
    email: "alinamath@gmail.com",
    mobile: "+91 8805322849",
    amountWithdrawal: "4,290",
    requestedDate: "1 Feb 2024",
    walletAmount: "30,000",
    status: "Decline",
    approvalDate: "14 November, 2023",
    icon: profile3,
  },
  {
    id: 4,
    doctorName: "Lucas Legros",
    email: "alinamath@gmail.com",
    mobile: "+91 8805322849",
    amountWithdrawal: "4,290",
    requestedDate: "1 Feb 2024",
    walletAmount: "30,000",
    status: "Decline",
    approvalDate: "14 November, 2023",
    icon: profile4,
  },
  {
    id: 5,
    doctorName: "Shanelle Ziemann",
    email: "alinamath@gmail.com",
    mobile: "+91 8805322849",
    amountWithdrawal: "5,290",
    requestedDate: "1 Feb 2024",
    walletAmount: "30,000",
    status: "Paid",
    approvalDate: "15 December, 2023",
    icon: profile5,
  },
  {
    id: 6,
    doctorName: "William Stephan",
    email: "alinamath@gmail.com",
    mobile: "+91 8805322849",
    amountWithdrawal: "5,290",
    requestedDate: "1 Feb 2024",
    walletAmount: "30,000",
    status: "Paid",
    approvalDate: "15 December, 2023",
    icon: profile6,
  },
  {
    id: 7,
    doctorName: "Smith Birkin",
    email: "alinamath@gmail.com",
    mobile: "+91 8805322849",
    amountWithdrawal: "5,290",
    requestedDate: "1 Feb 2024",
    walletAmount: "30,000",
    status: "Paid",
    approvalDate: "",
    icon: profile6,
  },
];